---
title: "Emissions Analysis"
author: "Rahul, Jiajia and Ignacia"
date: "April 21, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)

```

```{r databases}
# Importing data bases of emission factors for 2000 and 2007

ef_2000 <- read_csv(here("Databases/Emission_factors_2000.csv"))

ef_2007 <- read_csv(here("Databases/emission_factors_2007.csv"))
```

```{r data wrangling}
# Adding combusted and noncombusted emissions for 2007

ef_2007 <- ef_2007 %>% 
  mutate(co2 = co2_c + co2_nc, ch4 = ch4_c + ch4_nc, n2o = n2o_c + n2o_nc, sox = sox_c+sox_nc, nox= nox_c + nox_nc, pm10= pm10_c + pm10_nc, pm2.5= pm2.5_c + pm2.5_nc) %>% 
  select(industry= Industry, co2, ch4, n2o, sox, nox, pm10, pm2.5)

# List of industries that are in 2007 but not in 2000 (some of them are present in both but small changes in the wording made R to recognize them as different). Just to check if there are relevant industries related to food that differ between years.

diff_industry <- data.frame(ef_2007$industry[!(ef_2007$industry %in% ef_2000$industry)])

# Selecting food related industries based on list in the final power point

ef_2000 <- ef_2000 %>% 
  filter(industry %in% c("Cultivation of paddy rice", "Cultivation of wheat", "Cultivation of cereal grains nec", "Processed rice", "Cattle farming","Processing of meat cattle", "Pigs farming", "Processing of meat pigs", "Poultry farming",   "Processing of meat poultry", "Meat animals nec","Production of meat products nec", "Manufacture of fish products", "Processing of dairy products", "Raw milk", "Cultivation of vegetables, fruit, nuts", "Cultivation of sugar cane, sugar beet", "Sugar refining", "Cultivation of oil seeds", "Processing vegetable oils and fats", "Manufacture of beverages"))

ef_2007 <- ef_2007 %>% 
  filter(industry %in% c("Cultivation of paddy rice", "Cultivation of wheat", "Cultivation of cereal grains nec", "Processed rice", "Cattle farming","Processing of meat cattle", "Pigs farming", "Processing of meat pigs", "Poultry farming",   "Processing of meat poultry", "Meat animals nec","Production of meat products nec", "Manufacture of fish products", "Processing of dairy products", "Raw milk", "Cultivation of vegetables, fruit, nuts", "Cultivation of sugar cane, sugar beet", "Sugar refining", "Cultivation of oil seeds", "Processing vegetable oils and fats", "Manufacture of beverages"))

# Transforming into tidy data (better for working in R)

ef_2000 <- ef_2000 %>% 
  gather(key = pollutant, value = emission_factor, - industry) %>% 
  mutate(year= 2000)

ef_2007 <- ef_2007 %>% 
  gather(key = pollutant, value = emission_factor, - industry) %>% 
  mutate(year= 2007)
  
ef <- bind_rows(ef_2000, ef_2007)

```


```{r Creating new categories}

ef <- ef %>% 
  mutate(new_industry = ifelse(industry %in% c("Cultivation of paddy rice", "Cultivation of wheat", "Cultivation of cereal grains nec","Processed rice"), "cereal", ifelse( industry %in% c("Cattle farming","Processing of meat cattle"), "beef", ifelse(industry %in% c("Pigs farming", "Processing of meat pigs"), "pork", ifelse(industry %in% c("Poultry farming",   "Processing of meat poultry"), "poultry", ifelse(industry %in% c("Meat animals nec","Production of meat products nec"), "meat_other", ifelse(industry %in% c("Manufacture of fish products"), "fish", ifelse(industry %in% c("Processing of dairy products", "Raw milk"), "dairy", ifelse(industry %in% c("Cultivation of vegetables, fruit, nuts"), "vegs", ifelse(industry %in% c("Cultivation of sugar cane, sugar beet", "Sugar refining"), "sugar", ifelse(industry %in% c("Cultivation of oil seeds", "Processing vegetable oils and fats"), "oil", ifelse(industry %in% c("Manufacture of beverages"), "beverages",0))))))))))))

```

```{r Changes in emissions per contaminant type and industry}

changes_emissions <- ef %>% 
  group_by(industry, type) %>% 
  summarise(change = emissions[year==2007] - emissions[year==2000]) 

ggplot(changes_emissions, aes(industry, change, fill = industry)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  facet_wrap(~ type, ncol = 2, scales = "free") 

ggplot(filter(ef, year == 2000), aes(industry, emissions, fill = industry)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  facet_wrap(~ type, ncol = 2, scales = "free") 

ggplot(filter(ef, year == 2007), aes(industry, emissions, fill = industry)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())+
  facet_wrap(~ type, ncol = 2, scales = "free") 


```

```{r Next week}

# Weighting new industry emission factors based on final demand in EXIOBASE
# Try to code from raw EXIOBASE to emission factors
```

